config/routes.rb
# frozen_string_literal: true

require "mission_control/jobs"

# rubocop:disable Metrics/BlockLength
# rubocop:disable Style/FormatStringToken
Rails.application.routes.draw do
  get "diagnostics/index"
  get "diagnostics", to: "diagnostics#index"
  get "calendar_subscriptions/new"
  get "event_shifts/create"
  get "relationship_candidates/create"
  get "event_cancellations/new"
  get "event_cancellations/create"
  get "tags/create"
  get "integrations/index"
  get "welcome/index"
  get "", to: "web#index", constraints: ->(request) { request.subdomain =~ /\.sites/ }
  get "*path", to: "web#index", constraints: ->(request) { request.subdomain =~ /\.sites/ }
  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"
  mount BetterMailerPreviews::Engine, at: "/better_mailer_previews" if Rails.env.development?
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "welcome", to: "unit_membership_requests#new", as: "welcome"

  # %w[404 500].each do |code|
  #   get code, to: "errors#show", code: code
  # end

  devise_for :users, path: "", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions:           "users/sessions",
    registrations:      "users/registrations"
  }

  get "sms", to: "inbound_sms#receive"
  post "sms", to: "inbound_sms#receive"

  get "new_unit", to: redirect("/new_unit/start")
  get "new_unit/start", to: "new_unit#email"
  post "new_unit/confirm", to: "new_unit#confirm"
  get "new_unit/code", to: "new_unit#code"
  post "new_unit/check_code", to: "new_unit#check_code"
  get "new_unit/user_info", to: "new_unit#user_info"
  post "new_unit/save_user_info", to: "new_unit#save_user_info"
  get "new_unit/unit_info", to: "new_unit#unit_info"
  post "new_unit/save_unit_info", to: "new_unit#save_unit_info"
  get "new_unit/add_members", to: "new_unit#add_members"
  get "new_unit/add_member", to: "new_unit#add_member"
  post "new_unit/save_member", to: "new_unit#save_member"
  get "new_unit/import_member_list", to: "new_unit#import"
  post "new_unit/perform_import", to: "new_unit#perform_import"
  get "new_unit/communication_preferences", to: "new_unit#communication_preferences"
  post "new_unit/save_communication_preferences", to: "new_unit#save_communication_preferences"
  get "new_unit/done", to: "new_unit#done"

  get "callbacks/instagram", to: "instagram_external_integrations#callback"

  resources :event_activities, as: "activities"
  resources :event_shifts, only: [:create]
  resources :users, only: [:show, :update]

  # get "units/:unit_id/settings", as: "edit_unit_settings", to: "unit_settings#edit"
  # patch "units/:unit_id/settings", as: "update_unit_settings", to: "unit_settings#update"

  get "units/*after", to: redirect("/u/%{after}")
  get "u/:unit_id/schedule/repeat_options/:starts_at", to: "events#repeat_options", as: "repeat_options"

  # resources :payments, only: [:create]
  post "stripe", to: "stripe#create"

  namespace :base, path: "/" do
    resources :events, only: [:show]
  end

  resources :relationship_candidates, only: [:create]

  # begin units
  resources :units, path: "u", only: %i[show index update] do
    # post "search", to: "search#index", as: "search"
    # get "search", to: "search#new", as: "new_search"
    #
    resources :searches

    resources :document_sets, only: [:new] do
      collection do
        patch "update", as: "update"
        delete "destroy"
      end
    end

    scope module: :units do
      resources :documents, path: "library" do
        collection do
          # get "files", to: "documents#tag", as: "files"
          # get "list", as: "list"
          post "batch_update"
          post "batch_delete"
          post "batch_tag"
          post "batch_untag"
        end
      end
    end

    resources :messages, path: "messages" do
      resources :message_attachments, path: "attachments", as: "attachments", only: [:destroy]
      post "duplicate"
      post "unpin", as: "unpin"
      collection do
        get  "drafts"
        get  "sent"
        get  "outbox"
        # post "recipients", as: "recipients"
        get  "addressables", as: "addressables"
        get  "select",     as: "select"
        post "commit",     as: "commit"

        resources :recipients, only: [:index], module: :messages do
          collection do
            post "resolve/:gid", to: "recipients#resolve", as: "resolve"
            post "resolve_tag/:tag_name", to: "recipients#resolve_tag", as: "resolve_tag"
          end
        end
      end

      # get "address_book/:type/:id", to: "messaging_address_book#show", as: "address_book"
    end

    resources :message_attachments
    resources :notifications, only: [:index] do
      collection do
        post "mark_all_as_read"
        post "mark_all_as_unread"
      end

      member do
        post "mark_as_read"
        post "mark_as_unread"
      end
    end

    resources :locations
    resources :location_candidates, only: [:create]

    resources :packing_lists do
      resources :packing_list_items
    end
    resources :plans, path: "planner"
    resources :event_categories do
      get "remove", as: "remove"
    end
    resources :event_rsvps, only: [:destroy]
    resources :news_items do
      post "enqueue", to: "news_items#enqueue", as: "enqueue"
      post "dequeue", to: "news_items#dequeue", as: "dequeue"
    end

    get "my_rsvps", to: "events#my_rsvps", as: "my_rsvps"
    get "start",    to: "units#start",     as: "start"
    get "welcome",  to: "units#welcome",   as: "welcome"

    resources :payments, module: :settings do
      collection do
        post "onboard"
        get "refresh"
        get "return_from_onboarding"
      end
    end

    resources :tags, only: [:create]

    resources :events, path: "schedule" do
      resources :chat_messages, as: "discussion", path: "discussion"
      resources :family_rsvps, only: [:new, :create]
      resources :event_rsvps, as: "rsvps", path: "rsvps" do
        collection do
          get "popup"
          post "batch", to: "event_rsvps#create_batch"
          post "batch_member", to: "event_rsvps#create_batch_member" # kludge alert
        end
      end
      resources :event_rsvps
      resources :payments, module: :events
      resources :online_payments, module: :events, only: [:new]
      resources :photos
      resources :event_attachments, path: "attachments", as: "attachments"
      resources :event_activities
      resources :event_organizers, as: "organizers", path: "organizers"
      resources :document_types
      resources :email_invitations, only: [:create]
      resources :event_reminders, path: "reminders", as: "reminders", only: [:create]
      resources :locations, module: :events
      member do
        get "dashboard", to: "event_dashboard#index", as: "dashboard"
        get "rsvp",      to: "events#show", as: "rsvp", defaults: { variation: "rsvp" }
        get "organizer_package"
      end
      collection do
        resource :calendar_subscription, only: [:new], path: "calendar_subscription"
        get "feed/:token", to: "calendar#index", as: "calendar_feed" # ICS link
        get "public",      to: "events#public", as: "public"
        get "signups",     to: "events#signups", as: "signups"
        get "slow_list"
        get "list"
        get "paged_list"
        get "threeup"
        get "threeup/:year/:month", to: "events#threeup"
        # get "calendar", to: redirect { |path_params, _|
        #   "/units/#{path_params[:unit_id]}/schedule/calendar/#{Date.today.year}/#{Date.today.month}"
        # }, as: "calendar_redirect"
        # get "calendar"
        get "calendar", to: "events#calendar", as: "calendar_redirect"
        get "calendar/:year/:month", to: "events#calendar", as: "calendar"
        get "spreadsheet", to: "events#spreadsheet"
        post "spreadsheet/rows", to: "spreadsheet_rows#create"
        post "batch_updates", to: "events/batch_updates#create"
        post "bulk_publish", module: "events"
      end
      # get   "rsvp", as: "edit_rsvps", to: "events#edit_rsvps"
      get   "history"
      get   "add_to_calendar"
      get   "cancel", to: "event_cancellations#new"
      post  "cancel", to: "event_cancellations#create", as: "cancellations"
      patch "rsvp", as: "send_rsvps", to: "events#create_or_update_rsvps"

      constraints CanAccessFlipperUI do
        namespace :admin, module: :events do
          get   "/", to: "admin#index"
          post  "/remind", to: "admin#remind"
        end
      end
    end

    resources :event_locations, only: [:create]
    resources :integrations
    resources :photos

    get "settings", to: "settings#index", as: "settings"
    get "settings/automated_messages", to: "settings#automated_messages", as: "automated_messages"
    get "settings/documents"
    # get "settings/payments", to: "settings#payments"
    get "settings/test_communications", to: "settings#test_communications", as: "test_communications"
    get "settings/:category", to: "settings#edit", as: "setting"

    # redirect the old /events path. We can probably get rid of this
    # https://stackoverflow.com/questions/38509769/rails-routes-redirect-a-wild-card-route
    get "/events/*after", to: redirect("/u/%{unit_id}/schedule/%{after}")

    resources :unit_memberships

    resources :unit_memberships, path: "members", as: "members" do
      post "invite", to: "unit_memberships#invite", as: "invite"

      member do
        get "profile", to: "profiles#index"
        get "profile/info", to: "profiles#edit", as: "info"
        get "profile/alerts", to: "profiles#alerts", as: "alerts"
        get "profile/display", to: "profiles#display", as: "display"
        get "profile/security", to: "profiles#security", as: "security"
      end

      collection do
        post "bulk_update", to: "unit_memberships#bulk_update"
        get  "import",      to: "unit_memberships_import#new"

app/models/packing_list_item.rb
class PackingListItem < ApplicationRecord
end

app/controllers/packing_list_items_controller.rb
class PackingListItemsController < UnitContextController
  before_action :find_packing_list
  before_action :find_packing_list_item, only: [:show, :edit, :update, :destroy]

  def create
    @packing_list_item = @packing_list.packing_list_items.create(packing_list_item_params)
    redirect_to unit_packing_list_path(current_unit, @packing_list)
  end

  def destroy
    @packing_list_item.destroy
    redirect_to unit_packing_list_path(current_unit, @packing_list)
  end

  def edit; end

  def new
    @packing_list_item = @packing_list.packing_list_items.new
  end

  def update
    @packing_list_item.update(packing_list_item_params)
    redirect_to unit_packing_list_path(current_unit, @packing_list)
  end

  private

  def find_packing_list
    @packing_list = current_unit.packing_lists.find(params[:packing_list_id])
  end

  def find_packing_list_item
    @packing_list_item = @packing_list.packing_list_items.find(params[:id])
  end

  def packing_list_item_params
    params.require(:packing_list_item).permit(:name, :description)
  end
end

app/views/packing_list_items/_back_to_packing_list.slim
= link_to unit_packing_list_path(current_unit, @packing_list),
    class: "text-center font-bold no-underline block w-full md:w-fit py-6 text-cyan-500 hover:text-cyan-600",
    id: "cancel_location_button",
    data: { turbo_action: "advance", turbo_frame: "main" } do
    
    i.fa-stack
      i.fa-regular.fa-circle.fa-stack-2x
      i.fa-solid.fa-arrow-left.fa-stack-1x

    = "#{@packing_list.name} packing list"

app/views/packing_list_items/_empty_state.slim
p.py-6.text-stone-500 This packing list is empty. Add some items to get started.

app/views/packing_list_items/_form.slim
= form_with model: [current_unit, @packing_list, @packing_list_item] do |f|
  section.py-2
    = f.label :name, class: "font-bold block mb-1"
    = f.text_field :name,
                   class: "w-full font-bold rounded border-stone-400 placeholder-stone-300 dark:bg-black dark:border-stone-500",
                   autofocus: true,
                   placeholder: "e.g. Sleeping bag",
                   autocomplete: "off"

  section.py-2
    = f.label :description, class: "font-bold block mb-1"
    = f.text_area :description,
                  class: "w-full font-bold rounded border-stone-400 placeholder-stone-300 dark:bg-black dark:border-stone-500 h-24",
                  placeholder: "",
                  autocomplete: "off"

  footer.py-2
    = f.submit f.object.new_record? ? "Add this item" : "Update this item", class: "font-bold text-brand-500 hover:text-brand-600 border rounded border-brand-500 hover:border-brand-600 px-4 py-2"

app/views/packing_list_items/_packing_list_item.slim
li.font-bold.py-2.actionable
  .flex.flex-row.justify-between
    div
      = packing_list_item.name

      = content_tag(:p, packing_list_item.description, class: "mt-2 text-sm text-stone-500") if packing_list_item.description.present?

    .actions.text-xs.hidden
      = link_to edit_unit_packing_list_packing_list_item_path(current_unit, @packing_list, packing_list_item),
                title: "Rename this item",
                class: "text-stone-400" do
        .fa-stack
          i.fa-regular.fa-circle.fa-stack-2x
          i.fa-solid.fa-pencil.fa-stack-1x

      = button_to unit_packing_list_packing_list_item_path(current_unit, @packing_list, packing_list_item),
                method: :delete,
                form: { class: "inline" },
                title: "Delete this item",
                class: "inline text-stone-400" do
        .fa-stack
          i.fa-regular.fa-circle.fa-stack-2x
          i.fa-solid.fa-trash.fa-stack-1x

app/views/packing_list_items/edit.html.slim
= turbo_frame_tag "main" do
  .max-w-xl.mx-auto
    header
      = render partial: "back_to_packing_list"
    header
      h1.text-3xl.font-bold
        = "Edit an item"

      p.font-bold.text-stone-500
        = @packing_list.name

    = render partial: "form"

app/views/packing_list_items/new.html.slim
= turbo_frame_tag "main" do
  .max-w-xl.mx-auto
    header
      = render partial: "back_to_packing_list"
    header
      h1.text-3xl.font-bold
        = "Add an item"

      p.font-bold.text-stone-500
        = @packing_list.name

    = render partial: "form"