config/routes.rb
# frozen_string_literal: true

require "mission_control/jobs"

# rubocop:disable Metrics/BlockLength
# rubocop:disable Style/FormatStringToken
Rails.application.routes.draw do
  get "diagnostics/index"
  get "diagnostics", to: "diagnostics#index"
  get "calendar_subscriptions/new"
  get "event_shifts/create"
  get "relationship_candidates/create"
  get "event_cancellations/new"
  get "event_cancellations/create"
  get "tags/create"
  get "integrations/index"
  get "welcome/index"
  get "", to: "web#index", constraints: ->(request) { request.subdomain =~ /\.sites/ }
  get "*path", to: "web#index", constraints: ->(request) { request.subdomain =~ /\.sites/ }
  get "/service-worker.js", to: "service_worker#service_worker"
  get "/manifest.json", to: "service_worker#manifest"
  mount BetterMailerPreviews::Engine, at: "/better_mailer_previews" if Rails.env.development?
  root to: "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "welcome", to: "unit_membership_requests#new", as: "welcome"

  # %w[404 500].each do |code|
  #   get code, to: "errors#show", code: code
  # end

  devise_for :users, path: "", controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions:           "users/sessions",
    registrations:      "users/registrations"
  }

  get "sms", to: "inbound_sms#receive"
  post "sms", to: "inbound_sms#receive"

  get "new_unit", to: redirect("/new_unit/start")
  get "new_unit/start", to: "new_unit#email"
  post "new_unit/confirm", to: "new_unit#confirm"
  get "new_unit/code", to: "new_unit#code"
  post "new_unit/check_code", to: "new_unit#check_code"
  get "new_unit/user_info", to: "new_unit#user_info"
  post "new_unit/save_user_info", to: "new_unit#save_user_info"
  get "new_unit/unit_info", to: "new_unit#unit_info"
  post "new_unit/save_unit_info", to: "new_unit#save_unit_info"
  get "new_unit/add_members", to: "new_unit#add_members"
  get "new_unit/add_member", to: "new_unit#add_member"
  post "new_unit/save_member", to: "new_unit#save_member"
  get "new_unit/import_member_list", to: "new_unit#import"
  post "new_unit/perform_import", to: "new_unit#perform_import"
  get "new_unit/communication_preferences", to: "new_unit#communication_preferences"
  post "new_unit/save_communication_preferences", to: "new_unit#save_communication_preferences"
  get "new_unit/done", to: "new_unit#done"

  get "callbacks/instagram", to: "instagram_external_integrations#callback"

  resources :event_activities, as: "activities"
  resources :event_shifts, only: [:create]
  resources :users, only: [:show, :update]

  # get "units/:unit_id/settings", as: "edit_unit_settings", to: "unit_settings#edit"
  # patch "units/:unit_id/settings", as: "update_unit_settings", to: "unit_settings#update"

  get "units/*after", to: redirect("/u/%{after}")
  get "u/:unit_id/schedule/repeat_options/:starts_at", to: "events#repeat_options", as: "repeat_options"

  # resources :payments, only: [:create]
  post "stripe", to: "stripe#create"

  namespace :base, path: "/" do
    resources :events, only: [:show]
  end

  resources :relationship_candidates, only: [:create]

  # begin units
  resources :units, path: "u", only: %i[show index update] do
    # post "search", to: "search#index", as: "search"
    # get "search", to: "search#new", as: "new_search"
    #
    resources :searches

    resources :document_sets, only: [:new] do
      collection do
        patch "update", as: "update"
        delete "destroy"
      end
    end

    scope module: :units do
      resources :documents, path: "library" do
        collection do
          # get "files", to: "documents#tag", as: "files"
          # get "list", as: "list"
          post "batch_update"
          post "batch_delete"
          post "batch_tag"
          post "batch_untag"
        end
      end
    end

    resources :messages, path: "messages" do
      resources :message_attachments, path: "attachments", as: "attachments", only: [:destroy]
      post "duplicate"
      post "unpin", as: "unpin"
      collection do
        get  "drafts"
        get  "sent"
        get  "outbox"
        # post "recipients", as: "recipients"
        get  "addressables", as: "addressables"
        get  "select",     as: "select"
        post "commit",     as: "commit"

        resources :recipients, only: [:index], module: :messages do
          collection do
            post "resolve/:gid", to: "recipients#resolve", as: "resolve"
            post "resolve_tag/:tag_name", to: "recipients#resolve_tag", as: "resolve_tag"
          end
        end
      end

      # get "address_book/:type/:id", to: "messaging_address_book#show", as: "address_book"
    end

    resources :message_attachments
    resources :notifications, only: [:index] do
      collection do
        post "mark_all_as_read"
        post "mark_all_as_unread"
      end

      member do
        post "mark_as_read"
        post "mark_as_unread"
      end
    end

    resources :locations
    resources :location_candidates, only: [:create]

    resources :packing_lists do
      resources :packing_list_items
    end
    resources :plans, path: "planner"
    resources :event_categories do
      get "remove", as: "remove"
    end
    resources :event_rsvps, only: [:destroy]
    resources :news_items do
      post "enqueue", to: "news_items#enqueue", as: "enqueue"
      post "dequeue", to: "news_items#dequeue", as: "dequeue"
    end

    get "my_rsvps", to: "events#my_rsvps", as: "my_rsvps"
    get "start",    to: "units#start",     as: "start"
    get "welcome",  to: "units#welcome",   as: "welcome"

    resources :payments, module: :settings do
      collection do
        post "onboard"
        get "refresh"
        get "return_from_onboarding"
      end
    end

    resources :tags, only: [:create]

    resources :events, path: "schedule" do
      resources :chat_messages, as: "discussion", path: "discussion"
      resources :family_rsvps, only: [:new, :create]
      resources :event_rsvps, as: "rsvps", path: "rsvps" do
        collection do
          get "popup"
          post "batch", to: "event_rsvps#create_batch"
          post "batch_member", to: "event_rsvps#create_batch_member" # kludge alert
        end
      end
      resources :event_rsvps
      resources :payments, module: :events
      resources :online_payments, module: :events, only: [:new]
      resources :photos
      resources :event_attachments, path: "attachments", as: "attachments"
      resources :event_activities
      resources :event_organizers, as: "organizers", path: "organizers"
      resources :document_types
      resources :email_invitations, only: [:create]
      resources :event_reminders, path: "reminders", as: "reminders", only: [:create]
      resources :locations, module: :events
      member do
        get "dashboard", to: "event_dashboard#index", as: "dashboard"
        get "rsvp",      to: "events#show", as: "rsvp", defaults: { variation: "rsvp" }
        get "organizer_package"
      end
      collection do
        resource :calendar_subscription, only: [:new], path: "calendar_subscription"
        get "feed/:token", to: "calendar#index", as: "calendar_feed" # ICS link
        get "public",      to: "events#public", as: "public"
        get "signups",     to: "events#signups", as: "signups"
        get "slow_list"
        get "list"
        get "paged_list"
        get "threeup"
        get "threeup/:year/:month", to: "events#threeup"
        # get "calendar", to: redirect { |path_params, _|
        #   "/units/#{path_params[:unit_id]}/schedule/calendar/#{Date.today.year}/#{Date.today.month}"
        # }, as: "calendar_redirect"
        # get "calendar"
        get "calendar", to: "events#calendar", as: "calendar_redirect"
        get "calendar/:year/:month", to: "events#calendar", as: "calendar"
        get "spreadsheet", to: "events#spreadsheet"
        post "spreadsheet/rows", to: "spreadsheet_rows#create"
        post "batch_updates", to: "events/batch_updates#create"
        post "bulk_publish", module: "events"
      end
      # get   "rsvp", as: "edit_rsvps", to: "events#edit_rsvps"
      get   "history"
      get   "add_to_calendar"
      get   "cancel", to: "event_cancellations#new"
      post  "cancel", to: "event_cancellations#create", as: "cancellations"
      patch "rsvp", as: "send_rsvps", to: "events#create_or_update_rsvps"

      constraints CanAccessFlipperUI do
        namespace :admin, module: :events do
          get   "/", to: "admin#index"
          post  "/remind", to: "admin#remind"
        end
      end
    end

    resources :event_locations, only: [:create]
    resources :integrations
    resources :photos

    get "settings", to: "settings#index", as: "settings"
    get "settings/automated_messages", to: "settings#automated_messages", as: "automated_messages"
    get "settings/documents"
    # get "settings/payments", to: "settings#payments"
    get "settings/test_communications", to: "settings#test_communications", as: "test_communications"
    get "settings/:category", to: "settings#edit", as: "setting"

    # redirect the old /events path. We can probably get rid of this
    # https://stackoverflow.com/questions/38509769/rails-routes-redirect-a-wild-card-route
    get "/events/*after", to: redirect("/u/%{unit_id}/schedule/%{after}")

    resources :unit_memberships

    resources :unit_memberships, path: "members", as: "members" do
      post "invite", to: "unit_memberships#invite", as: "invite"

      member do
        get "profile", to: "profiles#index"
        get "profile/info", to: "profiles#edit", as: "info"
        get "profile/alerts", to: "profiles#alerts", as: "alerts"
        get "profile/display", to: "profiles#display", as: "display"
        get "profile/security", to: "profiles#security", as: "security"
      end

      collection do
        post "bulk_update", to: "unit_memberships#bulk_update"
        get  "import",      to: "unit_memberships_import#new"

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @taggable_type = params[:taggable_type]
    @tag_name = params[:value]
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def switch(object_name, method, options = {}, checked_value = "1", unchecked_value = "0")
    content_tag(:span, class: "switch-wrapper #{options[:class]}", style: options[:style]) do
      check_box(
        object_name, method,
        { checked: options[:checked], disabled: options[:disabled],
          data: options[:data], role: "switch", class: "dp-switch #{options[:check_box_class]}" },
        checked_value, unchecked_value
      ) +
        label(object_name, method, class: "flex items-center") do
          content_tag(:div, class: "switch-container") do
            content_tag(:div, nil, class: "switch-button")
          end + content_tag(:span, options[:label], class: "ml-2 select-none")
        end
    end
  end

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Layout/MultilineOperationIndentation
  # rubocop:disable Layout/LineLength
  def double_throw_switch(object_name, method, options = {})
    content_tag(:span, class: "block dt-switch switch-wrapper #{options[:disabled] ? 'disabled' : ''} #{options[:wrapper_classes]}", data: { controller: "double-throw-switch" }) do
      radio_button(object_name, method, options[:left_value], { class: "left-value dp-switch", checked: options[:checked_left], disabled: options[:disabled] }) +
      radio_button(object_name, method, "nil", { class: "center-value dp-switch", checked: options[:checked_center], disabled: options[:disabled] }) +
      radio_button(object_name, method, options[:right_value], { class: "right-value  dp-switch", checked: options[:checked_right], disabled: options[:disabled] }) +
      content_tag(:span, class: "dt-switch-container switch-container #{options[:disabled] ? 'disabled' : ''}") do
        content_tag(:div, nil, class: "switch-button") +
        label(object_name, method, value: options[:left_value], class: "left-label", data: { action: "click->double-throw-switch#click", position: "left" }) { options[:left_label] } +
        label(object_name, method, "", value: "nil", class: "center-label", data: { action: "click->double-throw-switch#click", position: "center" }) { "dummy" } +
        label(object_name, method, value: options[:right_value], class: "right-label", data: { action: "click->double-throw-switch#click", position: "right" }) { options[:right_label] }
      end
    end
  end
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Layout/MultilineOperationIndentation
  # rubocop:enable Layout/LineLength

  def back_link_to(body, url, html_options = {})
    html_options[:class] ||= ""
    html_options[:class] += " block font-bold"
    link_to(url, html_options) do
      content_tag(:i, nil, class: "fa-solid fa-chevron-left mr-2") +
        body
    end
  end
end

app/views/tags/_tag_label.slim
- colors = colors_from_string(tag_name)

div.pl-2.pr-1.py-1.rounded.flex.flex-row.gap-2(style="background-color: #{colors[200]}; color: #{colors[800]}" class="#{visible ? '' : 'hidden'}" id="tag_label_#{tag_name.parameterize.underscore}" data-value="#{tag_name.parameterize.underscore}")
  = tag_name
  = button_tag type: "button",
               class: "hover:bg-black/10 hover:text-black/50 rounded px-px",
               data: { action: "tag-field#remove", tag_name: tag_name.parameterize.underscore } do
    i.fa-light.fa-times.fa-fw.fa-sm

app/views/tags/_tag_option.slim
li
  = label_tag "tag_#{tag.id}", class: "search-item flex flex-row items-center px-2 py-2 hover:bg-stone-100 rounded", for: "tag_#{tag_name}" do
    i.fa-light.fa-tag.fa-fw.text-stone-500.mr-1
    = tag_name

    = check_box_tag "#{taggable_type}[tag_list][]", tag_name, checked, id: "#{taggable_type}_tag_#{tag_name.parameterize.underscore}", class: "ml-auto", data: { action: "change->checkable-list#change", tag_id: tag_name.parameterize.underscore, value: tag_name.parameterize.underscore }

app/views/tags/_tag_section.slim
= render partial: "tags/tags_popup", locals: { taggable: taggable }

.py-2.relative
  details.relative#tags(data-event-edit-target="tagListWrapper")
    summary.flex.flex-row.justify-between.items-center.-mx-2.px-2.py-1.hover:bg-brand-100.rounded.cursor-pointer(class="active:-mx-[0.4rem]")
      .font-semibold = "Tags"
      i.fa-light.fa-plus.fa-fw

  .flex.flex-wrap.gap-1.text-xs#tag_tag_field(data-controller="tag-field" data-tag-field-checkable-list-outlet="#tags_popup")
    - ActsAsTaggableOn::Tag.for_tenant(current_unit.id).each do |tag|
      = render partial: "tags/tag_label", locals: { tag_name: tag.name, visible: taggable.tags.include?(tag) }

app/views/tags/_tags_popup.slim
css:
  #tags_popup { display: none; }
  body:has(details#tags[open]) #tags_popup { display: block; }

- taggable_type = taggable.class.name.underscore

// TAGS POPUP
#tags_popup.absolute.bg-white.text-sm.w-72.-ml-16.border.rounded-lg.drop-shadow-overhead.pt-2.mt-1.z-10(data-popper-placement="bottom-start" data-controller="searchable-list checkable-list" data-checkable-list-tag-field-outlet="#tag_tag_field" data-searchable-list-new-value-url-value="#{unit_tags_path(current_unit)}" data-searchable-list-taggable-type-value="#{taggable_type}")
  .px-2
    = search_field :tag_search,
        nil,
        class: "block w-full rounded px-2 py-2 mb-2 text-sm border border-stone-200 placeholder-stone-400",
        placeholder: "Search tags",
        autofocus: true,
        autocomplete: "off",
        data: { action: "input->searchable-list#search", searchable_list_target: "searchField" }

  / Hidden field ensures empty array is submitted when no tags are checked
  = hidden_field_tag "#{taggable_type}[tag_list][]", "", id: nil

  ul.max-h-72.overflow-y-auto#tag_list
    - ActsAsTaggableOn::Tag.for_tenant(current_unit.id).each do |tag|
      = render partial: "tags/tag_option", locals: { taggable_type: taggable_type, tag_name: tag.name, checked: taggable.tag_list.include?(tag.name) }

  p.p-2.text-stone-500.hidden(data-searchable-list-target="valueNotFoundPrompt")
    | Tag not found

  div.hidden(data-searchable-list-target="newValuePrompt")
    
    = button_tag type: "button",
                 class: "p-2 font-semibold hover:bg-stone-100 block w-full text-left",
                 data: { action: "searchable-list#addValue" } do
      i.fa-light.fa-plus.fa-fw.text-stone-500.mr-2
      | Create "
      span(data-searchable-list-target="newValueName")
      | "

app/views/tags/create.turbo_stream.slim
= turbo_stream.append "tag_list", partial: "tags/tag_option", locals: { tag_name: @tag_name, checked: true, taggable_type: @taggable_type }
= turbo_stream.append "tag_tag_field", partial: "tags/tag_label", locals: { tag_name: @tag_name, visible: true }